import LightnessExample from './LightnessExample';
import {useLayoutEffect,useMemo,useRef,useState} from 'react';
import {contrast,generateColumn} from './workspace';
import './guide.css';
import {scaleTones} from './scale';

const brands=[{name:'Harbor',seed:'#0071B2'},{name:'Ember',seed:'#F57C13'}];
function ScaleExample({active}:{active:boolean}){
 const strip=useRef<HTMLDivElement>(null);
 const [brand,setBrand]=useState(0),[mapping,setMapping]=useState(1),[weight,setWeight]=useState('400');
 const full=useMemo(()=>generateColumn({id:'example',name:'primary',seed:brands[brand].seed,pins:[]}),[brand]);
 const tones=useMemo(()=>scaleTones(full,mapping),[full,mapping]);
 const chosen=tones.find(t=>t.weight===weight)??tones[Math.floor(tones.length/2)];
 useLayoutEffect(()=>{if(!active)return;const row=strip.current;const selected=row?.querySelector<HTMLElement>('[aria-pressed=true]');if(row&&selected){const a=row.getBoundingClientRect(),b=selected.getBoundingClientRect();row.scrollLeft+=b.left-a.left-(a.width-b.width)/2;}},[active,chosen.id,mapping]);
 const whiteRatio=contrast(chosen.hex,'#FFFFFF');
 const ink=whiteRatio>=contrast(chosen.hex,'#000000')?'#FFFFFF':'#000000';
 return <div className="guide-example">
  <div className="example-controls"><fieldset><legend>Example brand</legend><div className="brand-options">{brands.map((b,i)=><button key={b.name} aria-pressed={brand===i} onClick={()=>setBrand(i)}>{b.name}</button>)}</div></fieldset><label>Scale mapping<select value={mapping} onChange={e=>{setMapping(Number(e.target.value));setWeight(e.target.value==='2'?'60':'400');}}><option value={0}>Univers · full grid</option><option value={1}>Genome</option><option value={2}>Carbon-style · approximate</option></select></label></div>
  <p className="example-origin">Starting color <strong>{brands[brand].seed}</strong> · <strong>{tones.length}</strong> displayed steps from the same 22-slot foundation</p>
  <div ref={strip} className="example-swatches" role="group" aria-label="Example shades">{tones.map(t=><button key={t.id} aria-pressed={chosen.id===t.id} aria-label={`Preview primary ${t.weight}, ${t.hex}`} style={{background:t.hex,color:contrast(t.hex,'#FFFFFF')>=contrast(t.hex,'#000000')?'#FFFFFF':'#000000'}} onClick={()=>setWeight(t.weight!)}><b>{t.weight}</b><span>{t.isUserDefined?'Base':t.hex}</span></button>)}</div>
  <p className="example-instruction">Select a shade to preview it as a button background. Switch between Harbor and Ember to see the same palette structure with different brand colors. This example leaves your workspace unchanged.</p>
  <div className="example-result"><div><span className="guide-label">A role you assign</span><code>button.background → primary.{chosen.weight}</code><p>The reference stays meaningful when the brand changes.</p></div><div className="example-button-preview"><span className="sample-button" style={{background:chosen.hex,color:ink}}>Continue</span><span>Illustrative button · {chosen.hex}</span></div></div>
  <p className="example-contrast" role="status">White text on this shade: <strong>{whiteRatio.toFixed(2)}:1</strong> — {whiteRatio>=4.5?'meets':'below'} the 4.5:1 normal-text target. The preview chooses black or white text for the stronger contrast.</p>
  <small>This is a learning example. It does not edit your palette or create component tokens.</small>
 </div>;
}
export default function Guide({hidden}:{hidden:boolean}){
 return <main id="guide" className="guide" hidden={hidden}>
  <a className="guide-back" href="#main">← Back to palette</a>
  <header className="guide-intro"><span className="guide-eyebrow">Genome guide</span><h1 tabIndex={-1}>Build a palette from your brand colors</h1><p>Enter your brand colors, generate supporting shades, and choose which steps to include. Use the contrast controls to check color pairs before applying them in your designs.</p></header>
  <nav className="guide-nav" aria-label="Guide chapters"><a href="#guide-generate">01 Add colors</a><a href="#guide-scale">02 Choose a scale</a><a href="#guide-shades">Edit shades</a><a href="#guide-apply">03 Use colors</a><a href="#guide-start">Save and export</a></nav>
  <section id="guide-generate" className="guide-section"><span className="guide-eyebrow">01 / Add colors</span><h2>Add your colors</h2><p>Start with a base color for each family. Add pins for other exact colors you need to keep within that family.</p><p>Genome generates supporting shades across 22 lightness slots. Your base and pinned colors retain their exact HEX values in the full palette. A selected scale can leave those colors out if their slots aren’t included.</p><details><summary>What does “lightness” mean here?</summary><p>It describes a color’s position between dark and light. Genome interpolates in OKLab, then adjusts generated shades toward CIELAB L* targets. The two steps serve different jobs: generating transitions and organizing their lightness. Exact inputs are preserved rather than forced to a target.</p></details></section>
  <section id="guide-scale" className="guide-section"><span className="guide-eyebrow">02 / Choose a scale</span><h2>Choose a scale</h2><p>A scale mapping selects shades from the generated palette and gives them labels.</p><p>Start with Genome or choose Univers to see all 22 slots. Compare the available mappings using your own colors.</p><p>Company-named mappings use Genome-generated colors at approximate positions inspired by those systems. They don’t contain the companies’ palettes or reproduce their generators.</p><ScaleExample active={!hidden}/></section>
  <section id="guide-shades" className="guide-section"><h2>Edit your shades</h2><p>Open <strong>Edit shades</strong> to change the current mapping, or choose <strong>Start with 100–950</strong> for a ten-shade starting point.</p>
   <ul className="guide-checklist"><li>Add or remove shades and give each a unique name. Your scale can contain 2–22 shades.</li><li>Renaming a shade changes its label. Removing one leaves the remaining colors unchanged.</li><li>Use <strong>Adjust lightness</strong> to select another available slot. Higher values select lighter positions.</li><li><strong>Apply shades</strong> saves the scale across every family. <strong>Reset edits</strong> restores the last applied scale; <strong>Cancel</strong> discards the draft and closes the editor.</li></ul>
   <p>A shade named <code>500</code> does not have a lightness of 500. In the starter scale, that label selects slot 55. Choosing slot 45 selects a darker shade while keeping the same label.</p>
   <LightnessExample/>
   <details><summary>Why are there fixed slots instead of a free slider?</summary><p>This version selects from Genome’s existing 22 CIELAB L* target slots. A slot already used by another step is unavailable, so your scale does not contain duplicate positions. The numbers are not HSL or OKLCH lightness values and are not contrast scores. Exact inputs sit near their measured lightness and retain their original HEX, so a slot is an organizing target, not a promise of an exact measurement.</p><p>The same targets apply across families. A bright yellow base and a dark blue base can therefore land at different numbered steps. Choosing the same label does not make every family equally suitable for a button or for text; check the actual foreground and background using Show contrast.</p></details>
   <details><summary>Where did my base color or pin go?</summary><p>It remains an exact input in the family editor and continues to shape generation. If its slot is not selected, it is absent from the displayed scale. You can select its slot to display it, or include it as an additional named color when exporting. If you need to look up an input’s slot, Original Genome JSON records it as l_target alongside that color’s HEX. Switching mappings keeps your applied Custom scale available in the dropdown.</p><p>For example, the starter highlight yellow #FFCF3D occupies slot 85. The 100–950 starter includes it as 200. Removing 200 omits that yellow from the selected scale without deleting or changing the base input.</p></details>
   <details><summary>What if I want to start over after applying?</summary><p>Reset edits only reverses changes made since you opened the editor. To replace an already applied custom scale, choose a predefined mapping, or use Start with 100–950 and Apply shades. The separate Reset workspace control under Help → Saving your work also resets your colors, pins and other workspace settings.</p></details>
  </section>
  <section id="guide-apply" className="guide-section"><span className="guide-eyebrow">03 / Apply</span><h2>Use the colors in your design</h2><p>A palette entry such as <code>primary.400</code> identifies a color. A token such as <code>button.background</code> identifies where you use it.</p><div className="guide-flow" aria-label="Palette to component"><div><span>Palette entry</span><strong>primary.400</strong><small>A color value</small></div><span aria-hidden="true">→</span><div><span>Role token</span><strong>button.background</strong><small>Your chosen reference</small></div><span aria-hidden="true">→</span><div><span>Component</span><strong>Primary button</strong><small>Uses the role token</small></div></div><p>You can assign different palette colors to that role for each brand or mode. Genome exports palette data; you create the role assignments in your design system.</p><p>Try the palette on a button, a field and a message. Check text, backgrounds, borders, hover and focus states. Repeat these checks for each brand and mode.</p></section>
  <section id="guide-start" className="guide-section"><h2>Save and export</h2><p>Applied changes are saved in this browser. They aren’t synced to an account, and clearing browser data can remove them.</p><p>Choose an export based on the colors you need:</p><ul className="guide-checklist"><li><strong>Selected scale JSON</strong> contains the displayed shades and their names. If base or pinned colors are missing from your selection, the export panel lists them and asks whether to include them as additional named colors or leave them out.</li><li><strong>Original Genome JSON</strong> contains all 22 slots per family, including exact base and pinned colors. The complete Figma import workflow remains unverified for this version.</li></ul><p>Neither download can restore an editing session. Including additional colors in an export leaves your palette and shade selection unchanged.</p><a className="guide-cta" href="#main">Return to your palette →</a></section>
  <section className="guide-section guide-reading"><h2>About Genome</h2><p>This version updates the interface and workflows around Kevin Muldoon’s original Genome palette generator. The original generation engine is preserved.</p><p>The articles below explain his approach to multi-brand palettes, lightness and token naming.</p><ul><li><a href="https://uxdesign.cc/the-genome-color-tool-28ce73b20768" target="_blank" rel="noreferrer">The Genome Color Tool ↗</a><span>Multi-brand intent, lightness grids and scale optimization.</span></li><li><a href="https://uxdesign.cc/stop-using-oklch-lightness-for-your-color-scale-02025deca49d" target="_blank" rel="noreferrer">Stop using OKLCH lightness for your color scale ↗</a><span>Why generating a color and measuring contrast are separate tasks.</span></li><li><a href="https://uxdesign.cc/how-to-name-tokens-in-a-design-system-5b218589dadc" target="_blank" rel="noreferrer">How to name tokens in a Design System ↗</a><span>The distinction between palette entries and contextual tokens.</span></li></ul><p>Articles may require membership. Quick controls and further resources are available under Help in the palette workspace.</p></section>
 </main>;
}
