import {Options} from './constants/weightedTargets';
import ContrastHelp from './ContrastHelp';

export default function PresetInfo({preset}:{preset:number}) {
  const item=Options[preset];
  const status=item.status==='native'?'Genome scale':item.status==='approximate'?'Approximate mapping':'Legacy mapping';
  return <><span id="scale-mapping-explanation" className="sr-only">Changes the displayed steps and labels. Colors are generated by Genome.</span><ContrastHelp key={preset} label="About this scale" content={<div className="scale-info-content">
    <strong>{item.label} · {status} · v1</strong>
    <p>Changes the displayed steps and labels. Colors are generated by Genome.</p>
    {item.status!=='native'&&<p><strong>Not an official palette.</strong></p>}
    <p>{item.description}</p>
    <small>Source reviewed {item.auditedOn}. This mapping stays fixed when the source changes.</small>
    <a href={item.source} target="_blank" rel="noreferrer">View source ↗</a>
    <small>Escape or tap outside to close.</small>
  </div>}/></>;
}
